In [1]:
import pandas as pd
df_neg=pd.read_csv('negative.csv')
print(df_neg)

       Unnamed: 0                     url label
0               0  diaryofagameaddict.com   bad
1               1        espdesign.com.au   bad
2               2      iamagameaddict.com   bad
3               3           kalantzis.net   bad
4               4   slightlyoffcenter.net   bad
...           ...                     ...   ...
75638      420459         23.227.196.215/   bad
75639      420460      apple-checker.org/   bad
75640      420461       apple-iclods.org/   bad
75641      420462      apple-uptoday.org/   bad
75642      420463       apple-search.info   bad

[75643 rows x 3 columns]


In [2]:
df_pos=pd.read_csv('positive.csv')
df_pos=df_pos[:75643]
print(df_pos)

       Unnamed: 0                                                url label
0           42767                                         01453.com/  good
1           42768              015fb31.netsolhost.com/bosstweed.html  good
2           42769            02bee66.netsolhost.com/lincolnhomepage/  good
3           42770  02ec0a3.netsolhost.com/getperson.php?personID=...  good
4           42771                                        032255.com/  good
...           ...                                                ...   ...
75638      118405               mojokawasaki.com/photos/midohio.html  good
75639      118406                                       mojthem.com/  good
75640      118407              mojtv.hr/kanal/tv-program/98/vox.aspx  good
75641      118408                      mokanbasketball.multiply.com/  good
75642      118409  mokellyreport.wordpress.com/2009/07/15/phi-bet...  good

[75643 rows x 3 columns]


In [3]:
frames=[df_pos,df_neg]
balanced_df=pd.concat(frames)
print(balanced_df)

       Unnamed: 0                                                url label
0           42767                                         01453.com/  good
1           42768              015fb31.netsolhost.com/bosstweed.html  good
2           42769            02bee66.netsolhost.com/lincolnhomepage/  good
3           42770  02ec0a3.netsolhost.com/getperson.php?personID=...  good
4           42771                                        032255.com/  good
...           ...                                                ...   ...
75638      420459                                    23.227.196.215/   bad
75639      420460                                 apple-checker.org/   bad
75640      420461                                  apple-iclods.org/   bad
75641      420462                                 apple-uptoday.org/   bad
75642      420463                                  apple-search.info   bad

[151286 rows x 3 columns]


In [4]:
balanced_df.drop('Unnamed: 0', inplace=True, axis=1)

In [5]:
balanced_df

url label
0                                             01453.com/  good
1                  015fb31.netsolhost.com/bosstweed.html  good
2                02bee66.netsolhost.com/lincolnhomepage/  good
3      02ec0a3.netsolhost.com/getperson.php?personID=...  good
4                                            032255.com/  good
...                                                  ...   ...
75638                                    23.227.196.215/   bad
75639                                 apple-checker.org/   bad
75640                                  apple-iclods.org/   bad
75641                                 apple-uptoday.org/   bad
75642                                  apple-search.info   bad

[151286 rows x 2 columns]

In [6]:
balanced_df = balanced_df.sample(frac = 1)

In [7]:
balanced_df

url label
6527   articles.orlandosentinel.com/keyword/lucinda-w...  good
71074                                 lsiingenieria.com/  good
64591                    joespizzakc.com/JoesKellys.html  good
67730  latimesblogs.latimes.com/entertainmentnewsbuzz...  good
63153                             zeismanita.com/6mji3wi   bad
...                                                  ...   ...
20235  s3-us-west-2.amazonaws.com/fg-business-data/se...   bad
1782   avppet.com/wp-includes/js/tinymce/plugins/medi...   bad
27498                   donaldsonquarterly.blogspot.com/  good
62136  investing.businessweek.com/research/stocks/peo...  good
60308               icarusfilms.com/new97/the_last_.html  good

[151286 rows x 2 columns]

In [8]:
balanced_df.to_csv('balanced_dataset.csv')

In [1]:
import pandas as pd
in_csv = 'balanced_dataset.csv'
number_lines = 151286
rowsize = 75643
for i in range(1,number_lines,rowsize):
    df = pd.read_csv(in_csv,
          header=None,
          nrows = rowsize,#number of rows to read at each loop
          skiprows = i)#skip rows that have been read
    out_csv = 'balanced' + str(i) + '.csv'
    df.to_csv(out_csv,
          index=False,
          header=False,
          mode='a',#append data to csv file
          chunksize=rowsize)

In [2]:
import numpy as np
import pandas as pd

train_data_source = 'balanced1.csv'
test_data_source = 'balanced75644.csv'

train_df = pd.read_csv(train_data_source, header=None)
test_df = pd.read_csv(test_data_source, header=None)
print(train_df)
print(test_df)
max_len=train_df[1].map(lambda x: len(x)).max()

# concatenate column 1 and column 2 as one text
for df in [train_df, test_df]:
    df[1] = df[1] + df[2]
    df = df.drop([2], axis=1)
    
# convert string to lower case 
train_texts = train_df[2].values 
train_texts = [s.lower() for s in train_texts] 

test_texts = test_df[2].values 
test_texts = [s.lower() for s in test_texts] 

            0                                                  1     2
0        6527  articles.orlandosentinel.com/keyword/lucinda-w...  good
1       71074                                 lsiingenieria.com/  good
2       64591                    joespizzakc.com/JoesKellys.html  good
3       67730  latimesblogs.latimes.com/entertainmentnewsbuzz...  good
4       63153                             zeismanita.com/6mji3wi   bad
...       ...                                                ...   ...
226924  38500  uaanow.com/admin/online/order.php?.rand=13Inbo...   bad
226925  45116  klettur.bk-sh.com/wp-content/themes/webstat/fi...   bad
226926  44484  hf0.hikonefabebppw.info/c0e4gac9fl\nwww.lavoro...   bad
226927  50613  forum.notebookreview.com/alienware-m14x/574845...  good
226928  27711  downloads.khinsider.com/game-soundtracks/album...  good

[226929 rows x 3 columns]
            0                                                  1     2
0       71107  lubbockonline.com/go/2011-04-15/sto

In [3]:
print(len(train_texts))

226929


In [4]:
print(max_len)

1364


In [5]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

# Tokenizer
tk = Tokenizer(num_words=None, char_level=True, oov_token='UNK')
tk.fit_on_texts(train_texts)

# construct a new vocabulary 
alphabet="abcdefghijklmnopqrstuvwxyz0123456789 ,;.!?:'\"/\\|_@#$%^&*~`+-=<>()[]{}"
char_dict = {}
for i, char in enumerate(alphabet):
    char_dict[char] = i + 1
    
# Use char_dict to replace the tk.word_index
tk.word_index = char_dict.copy() 
# Add 'UNK' to the vocabulary 
tk.word_index[tk.oov_token] = max(char_dict.values()) + 1

In [7]:
train_df.columns

Int64Index([0, 1, 2], dtype='int64')

In [12]:
train_df.head()

0                                                  1     2
0   6527  articles.orlandosentinel.com/keyword/lucinda-w...  good
1  71074                             lsiingenieria.com/good  good
2  64591                joespizzakc.com/JoesKellys.htmlgood  good
3  67730  latimesblogs.latimes.com/entertainmentnewsbuzz...  good
4  63153                          zeismanita.com/6mji3wibad   bad

In [13]:
test_df.head()

0                                                  1     2
0  71107  lubbockonline.com/go/2011-04-15/stone-sour-sho...  good
1  57303                              ns2.bobbavice.top/bad   bad
2  26474  dictionary.sensagent.com/société+de+transport+...  good
3  68270   le-center-minnesota.apartmenthomeliving.com/good  good
4  33868  en.wikipedia.org/wiki/Category:Companies_estab...  good

In [20]:
from keras.utils import to_categorical
train_class_list=list(train_df[2].values)


In [21]:
train_classes = pd.Categorical(pd.factorize(train_class_list)[0])
print (set(train_classes))

{0, 1}


In [22]:
print(train_classes[:10])

[0, 0, 0, 0, 1, 0, 0, 0, 1, 0]
Categories (2, int64): [0, 1]


In [23]:
from keras.utils import to_categorical
train_classes = to_categorical(train_classes)
print(train_classes[:10])

[[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]]


In [24]:
from keras.utils import to_categorical
test_class_list=list(test_df[2].values)
test_classes = pd.Categorical(pd.factorize(test_class_list)[0])
print (set(test_classes))

{0, 1}


In [25]:
from keras.utils import to_categorical
test_classes = to_categorical(test_classes)
print(test_classes[:10])

[[1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]


In [26]:

train_sequences = tk.texts_to_sequences(train_texts)
test_texts = tk.texts_to_sequences(test_texts)
# Padding
train_data = pad_sequences(train_sequences, maxlen=100, padding='post')
test_data = pad_sequences(test_texts, maxlen=100, padding='post')


In [27]:
# Convert to numpy array
train_data = np.array(train_data, dtype='float32')
test_data = np.array(test_data, dtype='float32')


In [28]:
print(tk.word_index)

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6, 'g': 7, 'h': 8, 'i': 9, 'j': 10, 'k': 11, 'l': 12, 'm': 13, 'n': 14, 'o': 15, 'p': 16, 'q': 17, 'r': 18, 's': 19, 't': 20, 'u': 21, 'v': 22, 'w': 23, 'x': 24, 'y': 25, 'z': 26, '0': 27, '1': 28, '2': 29, '3': 30, '4': 31, '5': 32, '6': 33, '7': 34, '8': 35, '9': 36, ' ': 37, ',': 38, ';': 39, '.': 40, '!': 41, '?': 42, ':': 43, "'": 44, '"': 45, '/': 46, '\\': 47, '|': 48, '_': 49, '@': 50, '#': 51, '$': 52, '%': 53, '^': 54, '&': 55, '*': 56, '~': 57, '`': 58, '+': 59, '-': 60, '=': 61, '<': 62, '>': 63, '(': 64, ')': 65, '[': 66, ']': 67, '{': 68, '}': 69, 'UNK': 70}


In [29]:
vocab_size = len(tk.word_index)
vocab_size

70

In [30]:
embedding_weights = [] #(71, 70)
embedding_weights.append(np.zeros(vocab_size)) # first row is pad

for char, i in tk.word_index.items(): # from index 1 to 70
    onehot = np.zeros(vocab_size)
    onehot[i-1] = 1
    embedding_weights.append(onehot)
embedding_weights = np.array(embedding_weights)

In [31]:
print(embedding_weights.shape) # first row all 0 for PAD, 69 char, last row for UNK
embedding_weights

(71, 70)


array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [32]:
import pandas as pd
import numpy as np
import time

from keras import layers
from keras.models import Sequential
from keras.layers import Dense, Activation,Flatten
from keras.preprocessing.text import Tokenizer, one_hot
from keras.preprocessing.sequence import pad_sequences

import sklearn
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

import matplotlib.pyplot as pl

In [33]:
import pandas as pd
import numpy as np

from keras import layers
from keras.models import Sequential
from keras.preprocessing.text import Tokenizer, one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.layers import Embedding, Conv1D, GlobalMaxPooling1D, Dense, Dropout, Flatten, MaxPooling1D, Input, Concatenate
from keras.models import load_model

import sklearn
from sklearn.model_selection import train_test_split
from sklearn.utils import class_weight
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

import matplotlib.pyplot as plt

In [35]:
embedding_dim = 100

# Deep CNN
model = Sequential()
model.add(Embedding(vocab_size, embedding_dim, input_length=100,trainable=False))
model.add(Conv1D(1024, 7, activation='relu',padding='same'))
model.add(MaxPooling1D())
model.add(Conv1D(1024, 7, activation='relu',padding='same'))
model.add(MaxPooling1D())
model.add(Conv1D(512, 5, activation='relu',padding='same'))
model.add(MaxPooling1D())
model.add(Conv1D(512, 3, activation='relu',padding='same'))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(2, activation='sigmoid'))
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])
model.summary()


# Fit model
history = model.fit(train_data[:10000],train_classes[:10000],
                    epochs=1,
                    verbose=True,
                    validation_data=(test_data[:6000], test_classes[:6000]),
                    batch_size=50)
loss, accuracy = model.evaluate(train_data, train_classes, verbose=True)
print("Training Accuracy: {:.4f}".format(accuracy))
loss, accuracy = model.evaluate(test_data, test_classes, verbose=False)
print("Testing Accuracy:  {:.4f}".format(accuracy))

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 100, 100)          7000      
_________________________________________________________________
conv1d_4 (Conv1D)            (None, 100, 1024)         717824    
_________________________________________________________________
max_pooling1d_4 (MaxPooling1 (None, 50, 1024)          0         
_________________________________________________________________
conv1d_5 (Conv1D)            (None, 50, 1024)          7341056   
_________________________________________________________________
max_pooling1d_5 (MaxPooling1 (None, 25, 1024)          0         
_________________________________________________________________
conv1d_6 (Conv1D)            (None, 25, 512)           2621952   
_________________________________________________________________
max_pooling1d_6 (MaxPooling1 (None, 12, 512)          